apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project-home.yaml
  - argocd-self.yaml
  - infra-namespaces.yaml
  - platform-agones.yaml
  - platform-shulker.yaml
  - app-mc.yaml
